### ISSUE TITLE
EPuckMonitor error under Linux

### ISSUE THREAD

**Issue by Faris-ma** [epfl-mobots/Create_VSCode_e-puck2#1]
The EPuckMonitor QT interface doesn't load because the provided paths to the libraries and the plugins are not correct. Changing the "Run EPuckMonitor" task to include "export QT_PLUGIN_PATH=$PathToTheIDEFolder/EPuck2Tools/Utils/monitor_linux64bit/build-qmake-Desktop_Qt_5_10_1_GCC_64bit-Release/plugins && export LD_LIBRARY_PATH=$PathToTheIDEFolder/EPuck2Tools/Utils/monitor_linux64bit/build-qmake-Desktop_Qt_5_10_1_GCC_64bit-Release/lib && $PathToTheIDEFolder/EPuck2Tools/Utils/monitor_linux64bit/EPuckMonitor" solves this issue.

**Comment by martantoine** [comment]
Hi,

Thanks a lot for letting us know your fix
However I am really wondering why you have the folder "build-qmake-Desktop_Qt_5_10_1_GCC_64bit-Release" inside "monitor_linux64bit", the folder structure should look something like
```
Utils
|--monitor_linux64bit
|      |--plugins
|      |--lib
|      |--*.o
|      |--....
```
Moreover it seems the first export's variable name is missing, could you please specify it

Thank you in advance

**Comment by Faris-ma** [comment]
Hello,
Thank you for replying to my message. I will edit it to include the missing export variable. As to why the folder "build-qmake-Desktop_Qt_5_10_1_GCC_64bit-Release" is inside "monitor_linux64bit", it is because the line 178 of the install script reads : `mv build-qmake-Desktop_Qt_5_10_1_GCC_64bit-Release $InstallPath/EPuck2Tools/Utils/monitor_linux64bit`. Maybe changing it to `mv build-qmake-Desktop_Qt_5_10_1_GCC_64bit-Release/* $InstallPath/EPuck2Tools/Utils/monitor_linux64bit` would help in getting the correct final file structure.
Again, thank you for taking the time to review this issue.
